services:
  converter:
    environment:
      RKNODE_ENROLLMENT_TOKEN_FILE: /run/secrets/rknode-enrollment-token
    secrets:
      - source: rknode-converter-enrollment-token
        target: rknode-enrollment-token
  inference:
    environment:
      RKNODE_ENROLLMENT_TOKEN_FILE: /run/secrets/rknode-enrollment-token
    secrets:
      - source: rknode-inference-enrollment-token
        target: rknode-enrollment-token

secrets:
  rknode-converter-enrollment-token:
    file: ./secrets/converter-enrollment-token
  rknode-inference-enrollment-token:
    file: ./secrets/inference-enrollment-token
