services:
  trainer:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${RKNODE_CUDA_DEVICE_COUNT:-1}
              capabilities: [gpu]
